services:
  web:
    build: .
    container_name: room_booking
    command: sh entrypoint.sh
    volumes:
      - .:/apps
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  postgres_data:
